democracyworks/ColoradoRLA

client/src/component/Login/SecondFactorForm.tsx

@teaforthecat helped me find the right place to do this on the client side because I wasn't getting anywhere with the Java classes. 
It doesn't need to be lowercased for the first factor because that is handled at the DB level, but it doesn't seem to work for the 2FA.
After the first login, the user sees `Enter challenge for user: COUNTYADMIN15` above the 2FA inputs -- so if we lowercased on the first factor, what they see here would change and would not match what they entered.

Lowercase username from state when sending to 2FA

---

server/eclipse-project/src/main/java/us/freeandfair/corla/csv/ColoradoBallotManifestParser.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/BallotManifestInfo.java
server/eclipse-project/src/main/java/us/freeandfair/corla/query/BallotManifestInfoQueries.java

https://www.pivotaltracker.com/story/show/158561107 store sequence start and end on ballot manifest info
Columns were added to ballot_manifest_info shown with `describe` here:
```
\d ballot_manifest_info;
| Table "public.ballot_manifest_info"                 |                        |           |          |         |
|-----------------------------------------------------+------------------------+-----------+----------+---------|
| Column                                              | Type                   | Collation | Nullable | Default |
...
| sequence_end                                        | bigint                 |           | not null |         |
| sequence_start                                      | bigint                 |           | not null |         |
| Indexes: …
```

[ballot-selection] add and store sequence_start, sequence_end

---

client/src/component/Login/SecondFactorForm.tsx

As we observed in CO, users attempting to log in with a non-lowercase username were stymied on the second factor log-in form. When the user enters their username as lowercase, both first- and second- factor forms work as expected. It stands to reason that we need to lowercase the username on both forms, since that would provide the same result as if the user had initially entered their username in lowercase.

Lowercase username parameter to login2F

---

client/src/component/Login/SecondFactorForm.tsx

[I lost a line](https://github.com/democracyworks/ColoradoRLA/commit/9e76a090eb95b5616afaf2e89aba656ddc45701b#diff-36d1e3a99b83fe02170a9b875ece8390L103) in an earlier PR. When CDOS tested, the second factor wasn't accepted.

[bug] The challenge response needs spaces

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java

This manifested as the sample count for a round drifting lower as the number of duplicate CVR IDs increased. For a round that had seven duplicate CVRs to audit, this skewed our calculations and pushed us into a third round when two should have sufficed.
To quote @gws from a Slack discussion: 
> CVR audit info objects contain two fields, `multiplicity` and `counted`. `multiplicity` is the number of times that a single CVR appears in the sequence (number of times it is "drawn") and `counted` is the number of times we have entered its information into the RLA calculations. Eventually, those two should be equal, but at the start of a new round if you draw a dupe from the previous round, that dupe CVR should have a `multiplicity` of 2 and a `counted` of 1, because we've seen it a second time …

2018 primary alamosa bugfix

---

server/eclipse-project/project_configuration/freeandfair_checkstyle.xml
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditDownload.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditList.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/BallotManifestInfo.java
server/eclipse-project/src/main/java/us/freeandfair/corla/query/BallotManifestInfoQueries.java
server/eclipse-project/src/main/java/us/freeandfair/corla/query/CastVoteRecordQueries.java
server/eclipse-project/src/main/resources/log4j.properties
server/eclipse-project/src/test/java/us/freeandfair/corla/controllers/BallotSelectionTest.java
test/smoketest/main.py

This change makes random selection based on the manifest instead of the CVR data. Rendered data from the selections is also from the manifest(mostly). There is a bunch of CVR stuff in the middle, but I think this will satisfy the requirement of not using CVR data to choose ballots.

Select ballots from manifest info

---

client/src/component/DOS/DefineAudit/ReviewPage.tsx

From my browser's console:
We get a string rather than a number, which is perfect for being in a template.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#Description
[🐛 in Tracker](https://www.pivotaltracker.com/story/show/159416669)

Show the risk limit with two digits of precision

---

README.md
docker-compose.yml
docker/Makefile
docker/server/Dockerfile

The main benefit of this change is no longer having to specify the version number in `docker-compose.yml`.

Improve Docker build process primarily for the server component

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java

This does not address the problem of consuming phantom CVRs downstream, it only provides us a pointer in the logs as to the source for forensics.
References
==========
- [Pivotal card](https://www.pivotaltracker.com/story/show/159943234)

Log on phantom CVR creation

---

client/src/component/DOS/DefineAudit/StandardizeContestsPageContainer.tsx

This fixes a small-ish bug I noticed when running through the audit definition process a few times in a few different ways. When uploading large standardized contest name files, timing issues could cause our standardization logic to think there were no canonical contest names uploaded and thus skip the step. This would usually happen only on the first run through the audit definition workflow, but the first run through is also the most important.
The current architecture of the audit definition workflow is highly asynchronous, to the point that we render the standardized contests page before the file upload is even complete. If no data is present in the database, it is possible to have renders that change standardized contest props more than two times but without new data, thus fooling …

Fix a bug where standardized contests would sometimes not display on first run

---

CHANGELOG.md
docker/Makefile

We leave some versions unspecified, like requiring Apache `httpd:2.4`, but we want to allow the patch versions to float without having to explicitly touch the Dockerfile. This way we receive security updates as they are released.

Always pull new base Docker images when building

---

test/smoketest/main.py

Fix bug in smoketest/main.py
File "./main.py", line 655, in dos_start                                                                                          
print("No contests to audit, status_code = %d" % r.status_code)                                                                 
UnboundLocalError: local variable 'r' referenced before assignment                                                                  
and log number of audited ballot when printing out ACVRs, for easier comparison
and reduce logging level for very verbose dashboard debugging printouts

[test] [fix] Better debugging for smoketest main.py

---

client/county.d.ts
client/json.d.ts
client/screen.css
client/src/action/county/auditBoardSignIn.ts
client/src/action/county/setNumberOfAuditBoards.ts
client/src/adapter/countyDashboardRefresh.ts
client/src/adapter/establishBoard.ts
client/src/component/County/AuditBoard/Page.tsx
client/src/component/County/Dashboard/AuditBoardNumberSelector.tsx
client/src/component/County/Dashboard/Main.tsx
client/src/component/County/Dashboard/Page.tsx
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/AuditBoardSignIn.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/AuditBoardSignOut.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CountyDashboardRefresh.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/IntermediateAuditReport.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SetAuditBoardCount.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/UpdateAuditInfo.java
server/eclipse-project/src/main/java/us/freeandfair/corla/json/CountyDashboardRefreshResponse.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java
server/eclipse-project/src/main/resources/us/freeandfair/corla/endpoint/endpoint_classes

This represents the work done so far on the multiple audit board support epic. Note that the base branch for this PR is the branch that will contain the work for the epic, as completing individual cards will not leave in the application in a deliverable state, and so cannot be individually merged to master.
**Features:**
- Audit boards are now represented as a map of audit board index number to audit board object
- Operations on county audit boards all now require an index to be specified to log the user in to a particular audit board.
- UI for selecting the number of audit boards and the buttons which will eventually allow the separate audit boards to log in now exists.
https://www.pivotaltracker.com/story/show/160018700

Pick and store audit board number

---

client/src/component/County/AuditBoard/Page.tsx
client/src/component/County/AuditBoard/PageContainer.tsx
client/src/component/County/AuditBoard/SignedInPage.tsx
client/src/component/County/Dashboard/Main.tsx
client/src/component/County/Dashboard/Page.tsx
client/src/component/County/Dashboard/PageContainer.tsx
client/src/component/County/NavMenu.tsx
client/src/component/RootContainer.tsx
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/AuditBoardSignIn.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/AuditBoardSignOut.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java

This PR edges us closer to multiple audit board support in the following ways:
- Once the admin has set the number of audit boards for the round, the audit board sign in buttons at the bottom of the page should adjust to match the number of boards selected and become active.
- When the county admin clicks a particular audit board button from that page, they should be redirected to the audit board sign-in page for that audit board
- The page title "Audit Board" should now also contain the number of the specific audit board (e.g. "Audit Board 1")
https://www.pivotaltracker.com/story/show/160020629
**TODO:**

Allow audit board members to sign in to a particular audit board

---

client/src/component/County/Dashboard/Main.tsx
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditDownload.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditList.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SetAuditBoardCount.java
server/eclipse-project/src/main/java/us/freeandfair/corla/json/CVRToAuditResponse.java
server/eclipse-project/src/main/java/us/freeandfair/corla/json/CountyDashboardRefreshResponse.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CVRAuditInfo.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CastVoteRecord.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/Round.java
server/eclipse-project/src/main/java/us/freeandfair/corla/persistence/BallotSequenceAssignmentConverter.java
server/eclipse-project/src/main/java/us/freeandfair/corla/report/CountyReport.java
server/eclipse-project/src/main/java/us/freeandfair/corla/util/BallotAssignment.java
server/eclipse-project/src/main/java/us/freeandfair/corla/util/BallotSequencer.java
server/eclipse-project/src/test/java/us/freeandfair/corla/model/CastVoteRecordTest.java
server/eclipse-project/src/test/java/us/freeandfair/corla/util/BallotAssignmentTest.java

**Ballot division:**
At a high level, the existing ballot sequence was left alone, with the audit board division overlaid on top of that sequence. The division only needs to be done once, resulting in an _index_ (the position that audit board is starting from in the full sorted ballot sequence), and a _count_ (the length of that audit board's segment, starting from its _index_) for each audit board.
The algorithm for dividing ballots works as follows:
- Divide the number of ballots to audit evenly across the audit boards, using integer division
- Take the remainder ballots and spread them across the audit boards, in audit board order
- Shuffle the result so the remainder ballots are not always biased toward the first audit boards across rounds.
The end result is a list that looks like …

Divide county pull list among the audit boards

---

test/smoketest/main.py

crtest county_audit works again with the multiple audit board support in the server.
Request examples:
POST /set-audit-board-count {"count": 1}
POST /audit-board-sign-in {"audit_board":[{"first_name":"j","last_name":"j","political_party":"Democratic Party"},{"first_name":"j","last_name":"j","political_party":"Republican Party"}],"index":0}
POST /sign-off-audit-round {"audit_board_index":0,"signatories":[{"first_name":"j","last_name":"j"},{"first_name":"j","last_name":"j"}]}

Crtest multiple audit boards

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ContestResult.java
server/eclipse-project/src/main/java/us/freeandfair/corla/util/BallotSequencer.java
server/eclipse-project/src/test/java/us/freeandfair/corla/controllers/BallotSelectionTest.java

Sorry for changing the Segment class, I couldn't figure out a cleaner way to integrate this.
The assumptions made about the order of CVRs was mistaken - CDOS wanted ballots sorted by storage bin, which necessitates joining to the ballot manifest one way or another. I had already had code to do this which I'm able to reuse.
The CVRs stored in `Segment` are intentionally unordered now (but continue to be in a Set) so that nobody assumes ordering. The final ordering is set when StartAuditRound is called. We also return the CVRs directly from the Segment, because we also have to audit phantom ballots (on behalf of the given dashboard) when the round starts, if any were pulled during selection.

Audit phantom ballots before round start and properly sort ballots

---

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRExportImport.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java

Now that we have contests spanning counties, we need to wait until all possible CVR exports have been uploaded before we can count the results and look for any ties.
By doing it at the time of CVR import, a contest that might have tied in a county - but not overall - gets placed in the DoSDashboards.contestsToAudit() when it has no business being there yet.

Don't try to handle ties in a County context

---

test/e-state-county/audit.bash
test/smoketest/main.py

Fix logic around when to sign-in (and /set-audit-board-count)
to make sure it happens each round.
And drop old periodic /sign-off-audit-round from days when that was
a way to go to lunch or get an interrim periodic report

fix: crtest audit board sign-in with extra rounds

---

client/screen.css
client/src/component/County/Audit/Wizard/ReviewStage.tsx

Avoids misclicks if people click twice on the first button.
[Pivotal card](https://www.pivotaltracker.com/story/show/160827012)

Move "next card" button on the review screen

---

client/src/component/County/Audit/Wizard/BallotAuditStage.tsx

Fixes an issue where consent is required to *un-check* the box.
No Pivotal card for this one at this time.

Only require no-consensus consent if we are checking the box

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java

Given a CVR ID, we should be able to tell whether we should mark it for a given `ComparisonAudit` like this: 
```java
final boolean covered = isCovering(cvrID);
final boolean targeted = contestResult().getAuditReason().isTargeted();
```
This would mean contests being audited for opportunistic benefits should have an audited sample count of 0. [Related to this bug](https://www.pivotaltracker.com/story/show/160826772)

A CVR counts as an audited sample if it was selected for an audit

---

server/eclipse-project/src/main/java/us/freeandfair/corla/asm/ASMTransitionFunction.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/Round.java
test/e-state-county/audit.bash

If County A and County B were both participating in some multi-county `Contest One` and County B had a second single-county `Contest Two`, the simple act of running out of ballots to audit in County B (low voter turnout?) would try to end all of County B's audits. That's fine for `Contest Two`, but if we end `Contest One`, then we'll never be able to achieve a risk limit and complete as hoped.
You can see this for yourself if you use `test/e-state-county/audit.bash`. I've fiddled with it so it's a little cleaner in the UI. That'll run an audit for each of the four contests. Two contests, `Prop 1` and `Prop 2` include all three counties, one contest, `Prop 3`, occurs in Alamosa and Arapaho, and the last, `Prop 4`, is only in Alamosa.

When a county runs out of ballots, we can only terminate single county audits

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/report/StateReport.java

This is the simplest way I could come up with, plus, ballot type might be interesting because along with the imprinted-id it is one of the things the auditors are supposed to check.

[phantom-record] add ballotType to State report

---

server/eclipse-project/script/rla_export/rla_export/sql/contest_comparison.sql
server/eclipse-project/script/rla_export/rla_export/sql/contest_detail.sql

I'm not yet sure if it's ok to remove that WHERE qualification from contest_comparison.sql and contest_detail.sql. But it might be that that count is always nonzero given the other joins in the query with the acvrs. I.e. if an ACVR has been entered, I'd think the cvr would have a non-zero counted.
On the other hand, assume the check was there for a reason, at least originally.
Currently necessary for: `#70 Only counts selections for the contest we care about`

rla_export: Remove WHERE cai.counted <> 0

---

CHANGELOG.md
server/eclipse-project/project_configuration/freeandfair_pmd_ruleset.xml
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CVRAuditInfo.java

The default choice for persisting a string seems to be `varchar(255)` which won't be sufficient for any realistic map of stuff to things.
I ran into this when trying to run a couple of audits for the 2018 Adams County primary. With XYZ contests on the ballot, our maps were too big to persist so we couldn't move through an audit: the first response would never save.

[API] Specify column types for map serialization

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/report/CountyReport.java

This shows the signatories for each round, rather than leaving boxes for them to sign. Since the sign-off form *is* their sign-off, having them physically sign paper is redundant.
Resolves [#161129234](https://www.pivotaltracker.com/story/show/161129234).

Show signatories from all rounds on the affirmation sheet

---

server/eclipse-project/src/main/java/us/freeandfair/corla/asm/ASMTransitionFunction.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/resources/log4j.properties
test/2.0-test-data/second-round-failure.sh
test/smoketest/main.py

Here's a PR that [resolves #161131395](https://www.pivotaltracker.com/story/show/161131395). In short, we should sign off on every round whether there's work to do or not.
If you read the commits in order, you should be able to playback the experience. The script in `d3bc8fc` should leave you in a stuck audit if you checkout the branch at that point; the branch at `49d9d70` should let you get through a second round.

ROUND_COMPLETE_EVENT should transition to WAITING_FOR_ROUND_SIGN_OFF

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java

With a large sample size in a round computing the audited prefix length is too expensive an operation. With 682 samples the request to the county dashboard took 10 seconds. Without it, the request took 0.2 seconds. This also makes the info more clear on the dashboard and we have wanted to do this for some time. This is the answer to the question: "How many ballots until the end of the round", truthfully. There  may be a place for audited prefix length, but I don't think it is on the dashboard.

[dashboard] change meaning of ballotsRemainingInCurrentRound

---

CHANGELOG.md
client/screen.css

There is a subtle issue where browsers are capturing user clicks and interpreting them as starting text selection rather than a button click. This makes it slightly harder to miss clicking a button by preventing text selection on the buttons on the audit board selection screen altogether.

Prevent text selection on audit buttons

---

docker/postgresql/Dockerfile
docker/postgresql/postgresql.conf

This is the version pof PostgreSQL that CDOS is using.  This PR adds a mostly-default config: `checkpoint_segments = 10` should stop the log-spam about checkpoints happening to frequently, and `log_min_messages=debug1` gets us a hair more insight. I have no idea why `Navajo` is the default timezone; UTC makes more sense to me.

Test against PostgreSQL 9.6

---

docker/server/Dockerfile

If we're going to be scaling our testing environment past laptop sizes, it might be useful to be able to run a profiler on a remote host. This PR [adds the YourKit agent][1] to the Dockerized application. Additionally, the test environment will need to open port `10001` for the profiler to connect to the agent.
I've successfully tested this on my machine:
[1]: https://www.yourkit.com/docs/java/help/docker.jsp

Profiling inside containers

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/persistence/Persistence.java

For those cases where we might want to deploy the server in a container to different places, we can provide the Hibernate URL as an environment variable to supersede what's hard coded in `default.properties`. While I was there, I noticed the JDBC batch size was fixed to 100. This might or might not be the best value - [Hibernate documentation mentions 10-50 as starting values](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#batch-jdbcbatch) - so let's not hard code it.

Database URL should be configurable

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyContestComparisonAudit.java

The CVR format shows no selections in the event of an overvote. To make the audit board selections match in the event of an overvote, we therefore have to exclude all selections when the audit board records an overvote in order to have a chance at matching the CVR if indeed there was an overvote.
More detail around this has been added to the code responsible for dealing with it.

Correctly identify overvotes submitted by an audit board

---

server/eclipse-project/src/main/java/us/freeandfair/corla/query/CastVoteRecordQueries.java

We inadvertently dropped the random order that was stored on round.audit_subsequence when we queried the cvrs in bulk during selection. This will put the order back.

[ballot-selection] restore random order after query for cvrs

---

CHANGELOG.md
server/eclipse-project/src/main/java/us/freeandfair/corla/json/DoSDashboardRefreshResponse.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java

A floor of zero is practical when the question is "how many things more do I need to touch?". There is a zero that you'll see until we get a value calculated, but that seems more accurate than `Integer.MIN_VALUE` as a magic number.
Resolves [#162392809](https://www.pivotaltracker.com/story/show/162392809)

Don't show negative numbers of estimated samples

---

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/IndicateHandCount.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/AuditStatus.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java
server/eclipse-project/src/main/java/us/freeandfair/corla/query/ComparisonAuditQueries.java

This is a short path to making the button safe. There are concerns about math and integrity of the audit being worked out, but I think this is a good start. I think this is an alternative to removing the button completely. 
With this, when the button is pressed the status is updated in the database but that is it. There is really no other effect yet.

[api] safe hand count button

---

client/src/component/DOS/Dashboard/ContestUpdates.tsx
client/src/component/DOS/Dashboard/CountyUpdates.tsx
client/src/component/DOS/DefineAudit/SelectContestsForm.tsx
client/src/util.ts

Resolves [#163591819](https://www.pivotaltracker.com/story/show/163591819).
Uses `Intl.Collator` comparator with built-in numeric sorting to accomplish the task. This has been supported in all major browsers since IE 11.

Fix sorting to accommodate numeric strings naturally

---

client/dos.d.ts
client/npm-shrinkwrap.json
client/package.json
client/src/adapter/standardizeContests.ts
client/src/component/DOS/DefineAudit/StandardizeContestsPage.tsx
client/src/component/DOS/DefineAudit/StandardizeContestsPageContainer.tsx
client/vendor.d.ts

Done as a part of research for [#163597303](https://www.pivotaltracker.com/story/show/163597303).
We present the closest match within a given threshold as the default value to make contest mapping go a bit faster.
**Blocked by `re-audit`**

Contest name suggestion

---

client/src/component/County/AuditBoard/PageContainer.tsx
client/src/component/County/Dashboard/AuditBoardNumberSelector.tsx
client/src/saga/county/dashboardRefreshOkSaga.ts
client/src/saga/county/sync.ts
client/src/saga/sync.ts

Resolves [#163605107](https://www.pivotaltracker.com/story/show/163605107).
I also caught a spot where we were sending a duplicate network request for the contests, which should be a nice overall speedup.
The saga refactoring is so we do a better job of following redux-saga idioms, which facilitate:
- Generator testability: by yielding effect descriptions you can test what a generator should be doing without causing it to invoke its actions
- Allowing called functions to return Promises in the future
**Wait until `re-audit` is merged before rebasing and merging.**

Refresh dashboard after audit board count set

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java

Check if the contest is auditing the cvr before un-counting it as a "targeted" discrepancy for the county dashboard.

[api] reaudit fix - cdb discrepancy count

---

server/eclipse-project/src/main/java/us/freeandfair/corla/util/NaturalOrderComparator.java
server/eclipse-project/src/test/java/us/freeandfair/corla/util/NaturalOrderComparatorTest.java

I thought it was weird that dates wouldn't work as sort-able values of storage locations.  With this they would.

[api] change storage location sort so first diff counts, not last

---

client/src/component/DOS/DefineAudit/StandardizeContestsPageContainer.tsx
client/src/component/DOS/DefineAudit/StartPage.tsx

Shortcuts taken to skip the standardize contests and choices pages. It is not required and this will remove need for the awkward dummy file workaround.

[ui] skip standardization pages if a file is not given

---

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java

There was a bug in reaudit after all. The audit status gets updated to IN_PROGRESS during unaudit and whether all the necessary ballots have been audited needs to get re-evaluated, and then the audit status will be corrected. This is done by calling updateStatus.
I also removed a finalize step from the start of round because that is handled in the sign off step.

[api] fix reaudit end of round bug

---

docker/Makefile
docker/server-yourkit/Dockerfile
docker/server-yourkit/docker.properties

Removes YourKit from the default server build. In most cases we do not need YourKit, but this leaves an easy way to use it if we need to.

Create a separate YourKit server build

---

client/screen.css
client/src/adapter/dosDashboardRefresh.ts
client/src/component/DOS/Dashboard/CountyUpdates.tsx
client/src/format.ts
client/src/types/dos.d.ts

- When the audit board count is set, display a new status
- When a file upload has failed, display a new status
Resolves: [#166013154](https://www.pivotaltracker.com/story/show/166013154), [#166013270](https://www.pivotaltracker.com/story/show/166013270)

Add two new statuses to the state dashboard

---

client/screen.css
client/src/component/County/Dashboard/MissedDeadlinePage.tsx
client/src/component/FileDownloadButtons.tsx
client/src/saga/county/uploadBallotManifestSaga.ts

Implements mockups we had for this widget, with the addition of the row error context displayed in a popover to avoid cluttering the page with potentially long rows.
Resolves [#166043306](https://www.pivotaltracker.com/story/show/166043306).

Re-style file download widget

---

client/src/component/County/Audit/EndOfRound/FinalReviewPageContainer.tsx
client/src/component/County/Audit/EndOfRound/PageContainer.tsx
client/src/component/County/Audit/EndOfRound/SignOffFormContainer.tsx
client/src/component/County/Audit/PageContainer.tsx
client/src/component/County/Audit/Wizard/BallotAuditStageContainer.tsx
client/src/component/County/Audit/Wizard/BallotListStageContainer.tsx
client/src/component/County/Audit/Wizard/Container.tsx
client/src/component/County/Audit/Wizard/ReviewStageContainer.tsx
client/src/component/County/AuditBoard/PageContainer.tsx
client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx
client/src/component/County/Dashboard/CVRExport/FormContainer.tsx
client/src/component/County/Dashboard/FileUploadContainer.tsx
client/src/component/County/Dashboard/PageContainer.tsx
client/src/component/DOS/Contest/OverviewPageContainer.tsx
client/src/component/DOS/County/DetailPageContainer.tsx
client/src/component/DOS/County/OverviewPageContainer.tsx
client/src/component/DOS/Dashboard/MainContainer.tsx
client/src/component/DOS/Dashboard/PageContainer.tsx
client/src/component/DOS/Dashboard/RoundContainer.tsx
client/src/component/DOS/DefineAudit/ReviewPageContainer.tsx
client/src/component/DOS/DefineAudit/SeedPageContainer.tsx
client/src/component/DOS/DefineAudit/SelectContestsPageContainer.tsx
client/src/component/DOS/DefineAudit/StartPageContainer.tsx
client/src/component/Login/Container.tsx
client/src/component/RootRedirectContainer.tsx
client/src/component/withPoll.tsx
client/src/component/withState.tsx
client/src/component/withSync.tsx

This matches the react-redux `connect` [documentation][1], and so makes the code easier to understand for newcomers.
[1]: https://react-redux.js.org/using-react-redux/connect-mapstate

Rename `select` to `mapStateToProps`

---

client/src/action/county/downloadCvrsToAuditCsv.ts
client/src/action/county/fetchCvrsToAudit.ts
client/src/component/County/Audit/EndOfRound/FinalReviewPage.tsx
client/src/types/json.d.ts
server/eclipse-project/script/rla_export/rla_export/__main__.py
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java
server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditDownload.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditList.java
server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SetAuditBoardCount.java
server/eclipse-project/src/main/java/us/freeandfair/corla/json/CVRToAuditResponse.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CastVoteRecord.java
server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java

This contains a reversion of PR #138, as well as introducing a new "previously audited" non-persisted CVR flag that the UI can use to filter ballots audited in previous rounds. 
Fixes [#166194453](https://www.pivotaltracker.com/story/show/166194453).

Fix infinite round loop under certain circumstances

---

client/src/component/DOS/County/DetailPage.tsx

Resolves [#166312524](https://www.pivotaltracker.com/story/show/166312524).

Breadcrumb typo: "County" -> "Counties"

---

client/src/action/county/deleteFile.ts
client/src/action/dos/deleteFileForCounty.ts
client/src/component/County/Dashboard/CVRExport/FormContainer.tsx
client/src/component/FileDownloadButtons.tsx
client/src/reducer/dos/deleteFileOk.ts
client/src/reducer/root.ts
client/src/types/action.d.ts

Resolves an issue Monica reported where a full refresh was required to see deleted files, giving the impression that the application had failed in production when the timeouts are longer.

Immediately show deleted files on the DOS dashboard

---

server/eclipse-project/src/main/java/us/freeandfair/corla/report/CountyReport.java

Using cells A-G instead of A-C to give it some room to breathe.

Affirmation text on the county report has more room

---

client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx
client/src/component/County/Dashboard/CVRExport/FormContainer.tsx

This now waits until a deep equality comparison on the props changes, ensuring that any prop change will remove the temporary spinner state.
Resolves [#166389664](https://www.pivotaltracker.com/story/show/166389664)

Remove spinners on CVR upload error

---

client/src/adapter/dosDashboardRefresh.ts
client/src/component/DOS/County/DetailPage.tsx
client/src/component/DOS/County/OverviewPage.tsx
client/src/format.ts
client/src/types/dos.d.ts

Also now handles audit board presence in subsequent rounds.
Resolves [#166386508](https://www.pivotaltracker.com/story/show/166386508).

Update DoS dashboard to handle multiple audit boards

---

server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java

The auditStatus was getting overwritten immediately when a ballot is submitted.

[api] don't set auditStatus if hand counting
