client/src/component/Login/PasswordForm.tsx, client/src/component/Login/SecondFactorForm.tsx
https://www.pivotaltracker.com/n/projects/2159591/stories/158505641
=> Move toLowerCase to 1F instead of 2F

client/src/component/DOS/DefineAudit/ReviewPage.tsx, client/src/component/DOS/DefineAudit/SelectContestsPage.tsx
Bare minimum here. We'll make a second pass on this.
=> [ui] add selected contests to review page

client/src/component/Login/SecondFactorForm.tsx
So that the login flow is similar to Colorado's SCORE system, we combine three inputs into one. Any whitespace will be stripped in process.
[Pivotal Story](https://www.pivotaltracker.com/story/show/158495148)
=> Use a single input field for 2FA challenge

server/eclipse-project/project_configuration/freeandfair_checkstyle.xml
Most of these chceks are ok, but it is our opinion that variable names don't have to conform to a standard.
=> [ci] remove parameter name constraints

README.md
Updated to include current project info, more contributors, etc.
=> Update README with current project info

CHANGELOG.md, RELEASE.md, client/package.json, docker-compose.yml, server/eclipse-project/pom.xml
Here's how we're currently preparing GitHub releases.
=> Prep for a bugfix release

client/src/component/DOS/DefineAudit/UploadFileButton.tsx
https://github.com/react-dropzone/react-dropzone/issues/276
=> MIME types for CSV type files are unreliable on Windows

test/smoketest/genelect.py
See file block comment (or pydoc3 genelect) for documentation,
and genelect.py -h for help
=> genelect.py: Generate test files for RLAtool

client/src/component/County/Dashboard/AuditBoardNumberSelector.tsx, client/src/component/County/Dashboard/Main.tsx, server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java, server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/ACVRUpload.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/UpdateAuditInfo.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java, server/eclipse-project/src/main/java/us/freeandfair/corla/util/PhantomBallots.java
https://www.pivotaltracker.com/story/show/160570283
=> Exclude phantom ballots from the ballot audit sequence

client/src/component/DOS/DefineAudit/SelectContestsForm.tsx
This is a shim to make the ui look like it fits the new model -> Each Contest Name must be unique.
=> [ui] only show uniq Contests based on name

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java, server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditDownload.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditList.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CastVoteRecord.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/ContestResult.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/CastVoteRecordQueries.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/ComparisonAuditQueries.java
As always, there's more refactoring we could do. This PR addresses PMD and FindBugs' valid concerns.
=> Code cleanup as inspired by the static analysis toolchain

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java, test/2.0-test-data/alamosa-manifest.sha256, test/2.0-test-data/test-plan.txt
it works, it is more accurate, not sure if it really solves all our problems
=> [asm] try to end the audit with a different check allAuditsComplete

client/src/component/County/Dashboard/AuditBoardNumberSelector.tsx
[Pivotal card](https://www.pivotaltracker.com/story/show/160826197)
=> Fix ballot count pluralization on the county dashboard

server/eclipse-project/src/main/java/us/freeandfair/corla/asm/ASMTransitionFunction.java, server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/Round.java
some things that come up while testing. If there is a case where there is nothing to do, at least the steps will be able to be taken to reach the next steps and complete the audit.
=> [fix] more handling of nothing to do without errors

test/smoketest/smoketest.bash
Fix smoketest restart regression in d969cde7
=> Fix smoketest restart regression from new jar name

CHANGELOG.md, server/eclipse-project/src/main/java/us/freeandfair/corla/report/CountyReport.java
Fixes [#160995337](https://www.pivotaltracker.com/story/show/160995337).
=> Show all audit board members on the affirmation sheet

client/src/component/County/Audit/Wizard/BallotAuditStage.tsx, client/src/component/County/Audit/Wizard/ReviewStage.tsx
This involves a pretty insignificant HTML change -- removing two divs -- as well as removing unused destructured props.
https://www.pivotaltracker.com/n/projects/2159591/stories/161131049
=> Remove "Vote for X" text from data entry and review screens

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/BallotSelection.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/StartAuditRound.java, server/eclipse-project/src/main/resources/log4j.properties, test/load/genrun.sh, test/load/manifest-5000.csv, test/load/readme.md, test/load/setgo.sh, test/smoketest/genelect.py, test/smoketest/main.py
Here is a script to generate lots of data and run an audit on something approaching a real audit. It helps to highlight our performance problems.
There are a lot of logging changes here and I could separate them out into a different commit or a different pull request
story: https://www.pivotaltracker.com/story/show/161063725
=> [load] genrun.sh script with logging changes

CHANGELOG.md, client/src/component/County/Dashboard/MissedDeadlinePage.tsx, client/src/config.ts
Resolves [#161157392](https://www.pivotaltracker.com/story/show/161157392).
Here's what it looks like; what do you think about the **bolding of the text?**
=> Add CDOS contact info

test/smoketest/main.py
oops. This reverts a mistake to commit `b345b5bf origin/genrun [load] genrun.sh script with logging changes` 
There are also some logging tweaks.
=> [test] main.py revert accidental change, more logging tweaks

docs/26_export_manual.md, server/eclipse-project/script/rla_export/rla_export/__main__.py, server/eclipse-project/script/rla_export/rla_export/sql/contests_by_county.sql
and improve documentation and code clarity.
=> Fix syntax error for 0 ballots to audit in round

server/eclipse-project/script/rla_export/rla_export/__main__.py
=> Fix another err for 0 ballots to audit in round

server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyDashboard.java
I think this is it but I'd like to test it some more.
=> [fix] correct ballotsRemainingInCurrentRound

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java
check other counties to see if this county has finished the audit they are waiting for so they don't have to go to round 2
=> [api] check other cdbs during signoff

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/SignOffAuditRound.java, test/load/genrun.sh, test/smoketest/main.py
also do the check when the county is done as well as not done
see https://www.pivotaltracker.com/story/show/161131911
=> [api] skip self during signoff notifyRoundComplete

CHANGELOG.md, client/src/component/DOS/Dashboard/ContestUpdates.tsx
It does what it says on the tin and resolves [#162710577](https://www.pivotaltracker.com/story/show/162710577).
=> Hand count button requires confirmation

client/src/action/county/deleteFile.ts, client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx, client/src/component/County/Dashboard/CVRExport/FormContainer.tsx, server/eclipse-project/src/main/java/us/freeandfair/corla/controller/DeleteFileController.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/DeleteFile.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CVRContestInfo.java, server/eclipse-project/src/main/java/us/freeandfair/corla/model/CastVoteRecord.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/CastVoteRecordQueries.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/CountyContestResultQueries.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/CountyQueries.java, server/eclipse-project/src/main/resources/us/freeandfair/corla/endpoint/endpoint_classes, server/eclipse-project/src/test/java/us/freeandfair/corla/query/CastVoteRecordQueriesTest.java
Each file that a county uploads can be deleted by clicking the button shown where the upload file button was.
https://www.pivotaltracker.com/story/show/162392813
=> Delete file buttons

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/ACVRUpload.java
I overlooked this scenario in my testing
=> [api] don't advance state machine when reauditing

server/eclipse-project/src/main/java/us/freeandfair/corla/report/CountyReport.java, server/eclipse-project/src/main/java/us/freeandfair/corla/report/StateReport.java
Key changes:
- Summary sheet in landscape mode, set to fit on one page
- Round sheets set to fit on one page
- Affirmation page reworked to fit audit board members on a page without cutting them off
=> Enhance county report printability

server/eclipse-project/src/main/java/us/freeandfair/corla/csv/Result.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/UploadedFileQueries.java
=> [api] add equals to Result

CHANGELOG.md, client/package.json, client/src/adapter/countyDashboardRefresh.ts, client/src/adapter/dosDashboardRefresh.ts, client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx, client/src/component/County/Dashboard/CVRExport/FormContainer.tsx, client/src/component/FileDownloadButtons.tsx, client/src/types/index.d.ts, client/src/types/json.d.ts, server/eclipse-project/pom.xml, server/eclipse-project/src/main/java/us/freeandfair/corla/json/UploadedFileDTO.java, test/smoketest/main.py
addresses missing file names and removes duplicate attributes
=> Result on cdb

client/src/component/County/Dashboard/FileUploadContainer.tsx
Resolves [#166042931](https://www.pivotaltracker.com/story/show/166042931)
=> Remove manifest and CVR export matcher

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/DeleteFileController.java, server/eclipse-project/src/main/java/us/freeandfair/corla/query/ExportQueries.java, server/eclipse-project/src/main/resources/sql/cvr_hash.sql, server/eclipse-project/src/main/resources/sql/manifest_hash.sql, server/eclipse-project/src/main/resources/sql/upload_status.sql
update column name 
_and_ combine sql queries into one.
=> [api] update reports sql using uf.computed_hash

server/eclipse-project/src/main/java/us/freeandfair/corla/csv/ColoradoBallotManifestParser.java
Resolves [#166042827](https://www.pivotaltracker.com/story/show/166042827).
=> Throw error on invalid ballot manifests

server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRExportImport.java
fixes [#166312765](https://www.pivotaltracker.com/story/show/166312765)
=> [api] update the cdb.importStatus to show the progress bar

client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx, client/src/component/County/Dashboard/CVRExport/FormContainer.tsx
Resolves [#166312654](https://www.pivotaltracker.com/story/show/166312654).
=> Fix slow-to-appear upload spinner

client/src/action/dos/deleteFileForCounty.ts, client/src/component/County/Dashboard/BallotManifest/FormContainer.tsx, client/src/component/County/Dashboard/CVRExport/FormContainer.tsx, client/src/component/County/Dashboard/Main.tsx, client/src/component/DOS/County/DetailPage.tsx, client/src/component/DOS/County/DetailPageContainer.tsx, client/src/component/FileDownloadButtons.tsx, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/DeleteFile.java
This is working but polling is needed to see that the deletion has finished.
=> Delete file as the state

server/eclipse-project/src/main/java/us/freeandfair/corla/query/CountyContestResultQueries.java
this should solve the problem of file deletions taking too long
=> [api] fast contest delete

server/eclipse-project/src/main/java/us/freeandfair/corla/csv/ContestNameParser.java, server/eclipse-project/src/test/java/us/freeandfair/corla/csv/ContestNameParserTest.java
Resolves [#166390020](https://www.pivotaltracker.com/story/show/166390020).
=> Allow spaces in canonical choice names

server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRToAuditList.java, server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/IndicateHandCount.java, server/eclipse-project/src/main/resources/log4j.properties
=> Quieter logs
